In [ ]:
!pip install xgboost -q

In [ ]:
import xgboost
print("xgboost ok")

xgboost ok

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#LOAD DATASET

In [ ]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

print("Dataset shape:", X.shape)
X.head()

Dataset shape: (569, 30)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
print("Null values:", X.isnull().sum().sum())
print("Class counts:")
print(y.value_counts())

Null values: 0
Class counts:
1    357
0    212
Name: count, dtype: int64

#TRAIN/TEST SPLIT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape, X_test.shape)

(455, 30) (114, 30)

#SCALING

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

MODEL 1 : LOGISTIC REGRESSION

In [ ]:
# Logistic Regression Model

lr_model = LogisticRegression(max_iter=500)

lr_model.fit(X_train_scaled, y_train)

lr_pred = lr_model.predict(X_test_scaled)
lr_prob = lr_model.predict_proba(X_test_scaled)[:,1]

print("Logistic Regression trained")

Logistic Regression trained

In [ ]:
lr_acc = accuracy_score(y_test, lr_pred)
lr_prec = precision_score(y_test, lr_pred)
lr_rec = recall_score(y_test, lr_pred)
lr_f1 = f1_score(y_test, lr_pred)
lr_auc = roc_auc_score(y_test, lr_prob)
lr_mcc = matthews_corrcoef(y_test, lr_pred)

print("Accuracy:", lr_acc)
print("Precision:", lr_prec)
print("Recall:", lr_rec)
print("F1 Score:", lr_f1)
print("AUC:", lr_auc)
print("MCC:", lr_mcc)

Accuracy: 0.9736842105263158
Precision: 0.9722222222222222
Recall: 0.9859154929577465
F1 Score: 0.9790209790209791
AUC: 0.99737962659679
MCC: 0.9438975339262832

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, lr_pred))

print("\nClassification Report")
print(classification_report(y_test, lr_pred))

Confusion Matrix
[[41  2]
 [ 1 70]]

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

MODEL 2: DECISION TREE

In [ ]:
# Decision Tree Model

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)
dt_prob = dt_model.predict_proba(X_test)[:,1]

print("Decision Tree trained")

Decision Tree trained

In [ ]:
dt_acc = accuracy_score(y_test, dt_pred)
dt_prec = precision_score(y_test, dt_pred)
dt_rec = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)
dt_auc = roc_auc_score(y_test, dt_prob)
dt_mcc = matthews_corrcoef(y_test, dt_pred)

print("Accuracy:", dt_acc)
print("Precision:", dt_prec)
print("Recall:", dt_rec)
print("F1 Score:", dt_f1)
print("AUC:", dt_auc)
print("MCC:", dt_mcc)

Accuracy: 0.9473684210526315
Precision: 0.9577464788732394
Recall: 0.9577464788732394
F1 Score: 0.9577464788732394
AUC: 0.9439895185063871
MCC: 0.8879790370127744

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report")
print(classification_report(y_test, dt_pred))

Confusion Matrix
[[40  3]
 [ 3 68]]

Classification Report
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

MODEL 3: KNN

In [ ]:
# KNN Model

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train_scaled, y_train)

knn_pred = knn_model.predict(X_test_scaled)
knn_prob = knn_model.predict_proba(X_test_scaled)[:,1]

print("KNN trained")

KNN trained

In [ ]:
knn_acc = accuracy_score(y_test, knn_pred)
knn_prec = precision_score(y_test, knn_pred)
knn_rec = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)
knn_auc = roc_auc_score(y_test, knn_prob)
knn_mcc = matthews_corrcoef(y_test, knn_pred)

print("Accuracy:", knn_acc)
print("Precision:", knn_prec)
print("Recall:", knn_rec)
print("F1 Score:", knn_f1)
print("AUC:", knn_auc)
print("MCC:", knn_mcc)

Accuracy: 0.9473684210526315
Precision: 0.9577464788732394
Recall: 0.9577464788732394
F1 Score: 0.9577464788732394
AUC: 0.9819849328529315
MCC: 0.8879790370127744

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, knn_pred))

print("\nClassification Report")
print(classification_report(y_test, knn_pred))

Confusion Matrix
[[40  3]
 [ 3 68]]

Classification Report
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

MODEL 4: NAIVE BAYES

In [ ]:
# Naive Bayes Model

nb_model = GaussianNB()

nb_model.fit(X_train_scaled, y_train)

nb_pred = nb_model.predict(X_test_scaled)
nb_prob = nb_model.predict_proba(X_test_scaled)[:,1]

print("Naive Bayes trained")

Naive Bayes trained

In [ ]:
nb_acc = accuracy_score(y_test, nb_pred)
nb_prec = precision_score(y_test, nb_pred)
nb_rec = recall_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred)
nb_auc = roc_auc_score(y_test, nb_prob)
nb_mcc = matthews_corrcoef(y_test, nb_pred)

print("Accuracy:", nb_acc)
print("Precision:", nb_prec)
print("Recall:", nb_rec)
print("F1 Score:", nb_f1)
print("AUC:", nb_auc)
print("MCC:", nb_mcc)

Accuracy: 0.9649122807017544
Precision: 0.958904109589041
Recall: 0.9859154929577465
F1 Score: 0.9722222222222222
AUC: 0.9973796265967901
MCC: 0.9252853920667758

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, nb_pred))

print("\nClassification Report")
print(classification_report(y_test, nb_pred))

Confusion Matrix
[[40  3]
 [ 1 70]]

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

MODEL 5: RANDOM FOREST

In [ ]:
# Random Forest Model

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
rf_prob = rf_model.predict_proba(X_test)[:,1]

print("Random Forest trained")

Random Forest trained

In [ ]:
rf_acc = accuracy_score(y_test, rf_pred)
rf_prec = precision_score(y_test, rf_pred)
rf_rec = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_auc = roc_auc_score(y_test, rf_prob)
rf_mcc = matthews_corrcoef(y_test, rf_pred)

print("Accuracy:", rf_acc)
print("Precision:", rf_prec)
print("Recall:", rf_rec)
print("F1 Score:", rf_f1)
print("AUC:", rf_auc)
print("MCC:", rf_mcc)

Accuracy: 0.9649122807017544
Precision: 0.958904109589041
Recall: 0.9859154929577465
F1 Score: 0.9722222222222222
AUC: 0.9952505732066819
MCC: 0.9252853920667758

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, rf_pred))

print("\nClassification Report")
print(classification_report(y_test, rf_pred))

Confusion Matrix
[[40  3]
 [ 1 70]]

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

MODEL 6: XGBOOST

In [ ]:
# XGBoost Model

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    use_label_encoder=False,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)
xgb_prob = xgb_model.predict_proba(X_test)[:,1]

print("XGBoost trained")

XGBoost trained

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [12:10:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [ ]:
xgb_acc = accuracy_score(y_test, xgb_pred)
xgb_prec = precision_score(y_test, xgb_pred)
xgb_rec = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
xgb_auc = roc_auc_score(y_test, xgb_prob)
xgb_mcc = matthews_corrcoef(y_test, xgb_pred)

print("Accuracy:", xgb_acc)
print("Precision:", xgb_prec)
print("Recall:", xgb_rec)
print("F1 Score:", xgb_f1)
print("AUC:", xgb_auc)
print("MCC:", xgb_mcc)

Accuracy: 0.956140350877193
Precision: 0.9583333333333334
Recall: 0.971830985915493
F1 Score: 0.965034965034965
AUC: 0.9931215198165738
MCC: 0.9063785942932301

In [ ]:
print("Confusion Matrix")
print(confusion_matrix(y_test, xgb_pred))

print("\nClassification Report")
print(classification_report(y_test, xgb_pred))

Confusion Matrix
[[40  3]
 [ 2 69]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        43
           1       0.96      0.97      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

COMPARISON OF MODELS

In [ ]:
results_table = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "KNN",
        "Naive Bayes",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        lr_acc, dt_acc, knn_acc, nb_acc, rf_acc, xgb_acc
    ],
    "AUC": [
        lr_auc, dt_auc, knn_auc, nb_auc, rf_auc, xgb_auc
    ],
    "Precision": [
        lr_prec, dt_prec, knn_prec, nb_prec, rf_prec, xgb_prec
    ],
    "Recall": [
        lr_rec, dt_rec, knn_rec, nb_rec, rf_rec, xgb_rec
    ],
    "F1": [
        lr_f1, dt_f1, knn_f1, nb_f1, rf_f1, xgb_f1
    ],
    "MCC": [
        lr_mcc, dt_mcc, knn_mcc, nb_mcc, rf_mcc, xgb_mcc
    ]
})

results_table

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.973684,0.997380,0.972222,0.985915,0.979021,0.943898
1,Decision Tree,0.947368,0.943990,0.957746,0.957746,0.957746,0.887979
2,KNN,0.947368,0.981985,0.957746,0.957746,0.957746,0.887979
3,Naive Bayes,0.964912,0.997380,0.958904,0.985915,0.972222,0.925285
4,Random Forest,0.964912,0.995251,0.958904,0.985915,0.972222,0.925285
5,XGBoost,0.956140,0.993122,0.958333,0.971831,0.965035,0.906379

In [ ]:
!pip install joblib -q

In [ ]:
import joblib

In [ ]:
joblib.dump(lr_model, "logistic_model.pkl")
joblib.dump(dt_model, "decision_tree_model.pkl")
joblib.dump(knn_model, "knn_model.pkl")
joblib.dump(nb_model, "naive_bayes_model.pkl")
joblib.dump(rf_model, "random_forest_model.pkl")
joblib.dump(xgb_model, "xgb_model.pkl")

joblib.dump(scaler, "scaler.pkl")

print("All models and scaler saved")

All models and scaler saved

In [ ]:
import os
print(os.listdir())

['.config', 'scaler.pkl', 'requirements.txt', 'README.md', 'decision_tree_model.pkl', 'knn_model.pkl', 'xgb_model.pkl', 'breast_cancer_test.csv', 'logistic_model.pkl', '.ipynb_checkpoints', 'random_forest_model.pkl', 'app.py', 'naive_bayes_model.pkl', 'sample_data']

In [ ]:
readme_text = """
# Machine Learning Classification Assignment – Streamlit App

## Problem Statement
The goal of this project is to implement and compare multiple machine learning classification models on a real dataset. The models are trained and evaluated using standard performance metrics. An interactive Streamlit web app is created to allow users to upload a dataset and test different models.

## Dataset Description
I used the Breast Cancer Classification dataset from sklearn library.
It contains 569 samples and 30 numerical features.
The target variable has two classes representing malignant and benign tumors.

## Models Implemented
- Logistic Regression
- Decision Tree
- KNN
- Naive Bayes
- Random Forest
- XGBoost

## Metrics Used
Accuracy, AUC, Precision, Recall, F1 Score, MCC

(Fill metric table from notebook output)

## Streamlit Features
- CSV upload
- Model selection
- Metrics display
- Confusion matrix
- Classification report
"""

with open("README.md", "w") as f:
    f.write(readme_text)

print("README.md created")

README.md created

In [ ]:
# recreate dataset and save as CSV for Streamlit testing

from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="target")

df = pd.concat([X, y], axis=1)

df.to_csv("breast_cancer_test.csv", index=False)

print("CSV created")
df.head()

CSV created

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0